version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: refile_test
      POSTGRES_USER: refile_postgres_test_user
      POSTGRES_PASSWORD: refilepostgres
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: refile_postgres_test_user
      POSTGRES_PASSWORD: refilepostgres
      POSTGRES_DB: refile_test
volumes:
  gems:
    driver: local