name             'ruby'
maintainer       'Krists Ozols'
maintainer_email 'krists.ozols@gmail.com'
license          'MIT'
description      'Installs/Configures ruby-installer and chruby'
version          '0.1.0'
